### ISSUE TITLE
403 loop

### ISSUE THREAD

**Issue by moarlongcatplox** [skyride/evething-2#3]
When queried for information about structures, if the character is not on the acl, esi returns a 403.  In  esi.py, line 38 there's a comment that if it throws a 403 it's from an invalid token.  In typical :ccp: fashion, it appears that the 403 is used for not being allowed to see structure acls as well as not having an auth token. I'm no python genius, but I'll play around with it for a bit and see what I can come up with. 

```
[2017-05-24 20:48:24,421: DEBUG/Worker-5] https://esi.tech.ccp.is:443 "GET /latest/universe/structures/1021542958222/?datasource=tranquility HTTP/1.1" 403 None
[2017-05-24 20:48:24,439: DEBUG/Worker-5] Starting new HTTPS connection (1): login.eveonline.com
[2017-05-24 20:48:25,072: DEBUG/Worker-5] https://login.eveonline.com:443 "POST /oauth/token HTTP/1.1" 200 337
[2017-05-24 20:48:25,101: DEBUG/Worker-5] (0.002) UPDATE `thing_esitoken` SET `access_token` = ' ... '
[2017-05-24 20:48:25,110: DEBUG/Worker-5] Starting new HTTPS connection (1): esi.tech.ccp.is
[2017-05-24 20:48:25,942: DEBUG/Worker-5] https://esi.tech.ccp.is:443 "GET /latest/universe/structures/1021542958222/?datasource=tranquility HTTP/1.1" 403 None

```
It will just repeat that until you kill celery. Sorry for the edit, pressed the wrong button.

**Comment by skyride** [comment]
Which task is this occurring on? CharacterInfo hits the wallet endpoint as its first request because it's nice and simple to avoid this.

I pushed a quick fix that should solve your issue, but I'm curious how it ended up there to begin with. If you could link a stack trace that would be dope.

**Comment by moarlongcatplox** [comment]
I'm not certain what the particular task is. The logs I put in there are from running celery with the debug flag so I could watch/log everything it's doing. With a brand new character added to the app, it starts pulling the skills, then moves on to assets, where I assume this is coming from. I'll figure out how to get you  a stack trace (as I said, I know jack about python development atm).  I'll post it here once I can.

**Comment by skyride** [comment]
Huh. Has to be CharacterInfo then. Even if you can just get me the full log of the endpoints its hitting that'd work.

If you turn on the Debug = True in local_settings, the ESI API will print the full URL for every endpoint it hits.

**Comment by moarlongcatplox** [comment]
Couple of things: I'm not sure where to find the full url for each endpoint, unless it's the ones in the celery logs. I went ahead and just attached the whole log that I got prior to applying your fix.  There are a couple of times when a 403 is returned but the jobs continue. For some reason, when it gets to that particular station, it just continuously requests, gets 403'd, then tries to get a new token. 

I'll try your fix now, but I wanted to submit so you'd have the information.  

Celery debug log with all the endpoints: [celerylog.txt](https://github.com/skyride/evething-2/files/1032102/celerylog.txt)

**Comment by moarlongcatplox** [comment]
Unfortunately, even after applying the fix in esi.py, it continues to do the same thing. When it gets to that particular structure (1021542958222), there's just an endless loop of 403, refresh token, 403,

**Comment by skyride** [comment]
So looking at this log, it's not actually an infinite loop. What's going on is it's running into that for every asset you have in that structure, so every asset you have there generates 2 blocking API requests and you have a lot of assets there so it's reallllly slow.

That's easily fixed, I'll just go implement a local cache on the ESI library and it should solve the problem.

**Comment by skyride** [comment]
And done!

**Comment by moarlongcatplox** [comment]
Indeed. I let it run all the way, rather than stopping it. It seemed like it was making the same request repeatedly, so I stopped it rather than getting rate-limited. Apparently that wasn't going to be an issue.  Fix seems good so far!

**Comment by skyride** [comment]
Tremendous
