### ISSUE TITLE
Completed Market Orders Do Not Get Removed

### ISSUE THREAD

**Issue by BuumEdzott** [skyride/evething-2#4]
When a market order is updated (e.g. when someone buys or sells to a portion of the order, or when the price point is changed), the order is accurately updated in the Orders window. However, upon order completion/deletion/expiry, the order is not removed and remains in its last-known state indefinitely.

**Comment by skyride** [comment]
Ah yeah I see why this is happening. Should be an easy 20 min thing to fix when I've got time tomorrow.

**Comment by skyride** [comment]
Sorted
