### ISSUE TITLE
Private contracts sometimes display as Public on the Contracts page

### ISSUE THREAD

**Issue by BuumEdzott** [skyride/evething-2#5]
Some contracts with private availability have their "Assigned To" displaying as "Public" on the contracts page. It seems like Public is displaying instead of certain corporations or characters, while in other cases the actual corporation or character to whom the contract is assigned is properly displayed.

Additionally, for affected contracts, viewing the page for that specific contract lists its availability as "Private - ".

There does not seem to be any rhyme or reason for which assignees are affected, but all contracts assigned to those players or corporations display as being assigned to "Public".

**Comment by skyride** [comment]
Yeah this is a known bug. It's something I'll get round to fixing this week.
