### ISSUE TITLE
Using /latest/ for ESI results in broken code when new endpoints versions are promoted

### ISSUE THREAD

**Issue by BuumEdzott** [skyride/evething-2#7]
Because the ESI class is set up to use `ESI_URL` as the base for all routes, it isn't possible to configure evething2 to use differently-versioned routes for different endpoints. As a result, when new versions of endpoints get rolled into `latest` (or whichever spec is chosen), various functionality can break until (1) the code accessing those endpoints is updated in the repo; and (2) the administrator performs a `git pull`.

For instance, a new `/corporations/{id}/` endpoint was recently promoted to `latest`, and as a result `corporation.py` fails on line 87 (because the field it is looking for has been removed), unless one has pulled in less-than-week-old changes from the repo.

If the endpoints were versioned separately (using, for instance, `/v4/corporations/{id/`), one could at least maintain functionality using the legacy version of the endpoint (as long as it gets updated before the legacy version is removed entirely).

**Comment by skyride** [comment]
All API calls are now versioned. Make sure to update your ESI_URL in local settings to remove "/latest"
